
<?php echo $this->tag->form("nilai/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("nilai", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Simpan") ?></td>
    </tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create nilai</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="ProgramSiswaRecId">ProgramSiswaRecId</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("ProgramSiswaRecId", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="Nilai1">Nilai1</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("Nilai1", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="Nilai2">Nilai2</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("Nilai2", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="Nilai3">Nilai3</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("Nilai3", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="Nilai4">Nilai4</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("Nilai4", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="Nilai5">Nilai5</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("Nilai5", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="Nilai6">Nilai6</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("Nilai6", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="Nilai7">Nilai7</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("Nilai7", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="Nilai8">Nilai8</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("Nilai8", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="Nilai9">Nilai9</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("Nilai9", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="Nilai10">Nilai10</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("Nilai10", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Simpan") ?></td>
    </tr>
</table>

</form>
