<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<h1>
    <?php echo $this->tag->linkTo(array("nilai/index", '<i class="icon-arrow-left-3 fg-darker smaller"></i>')); ?>
    Nilai

    <small class="on-right">Hasil pencarian</small>
</h1>

<table class="table bordered striped hovered" align="center">
    <thead>
        <tr>
            <th>No.</th>
            <th>Nama Program</th>
            <th>Kode Siswa</th>
            <th>Nama Siswa</th>
            <th>Bidang Studi</th>
            <th>Nilai1</th>
            <th>Nilai2</th>
            <th>Nilai3</th>
            <th>Nilai4</th>
            <th>Nilai5</th>
            <th>Nilai6</th>
            <th>Nilai7</th>
            <th>Nilai8</th>
            <th>Nilai9</th>
            <th>Nilai10</th>
            <th colspan="2">Action</th>
         </tr>
    </thead>
    <tbody>
    <?php 
    if(isset($page)){
        if($page->items != null){
            $i=1;
            if(isset($_GET['page'])){
                if(intval($_GET['page']) > 1) $i += (intval($_GET['page'])-1)*10;
            }
        }

        foreach ($page->items as $nilai) { ?>
        <tr>
            <td><?php echo $i."."; ?></td><?php $i++;?>
            <td><?php echo $nilai->NamaProgram ?></td>
            <td><?php echo $nilai->VirtualAccount ?></td>
            <td><?php echo $nilai->NamaSiswa ?></td>
            <td><?php echo $nilai->BidangStudi ?></td>
            <td><?php echo $nilai->Nilai1 ?></td>
            <td><?php echo $nilai->Nilai2 ?></td>
            <td><?php echo $nilai->Nilai3 ?></td>
            <td><?php echo $nilai->Nilai4 ?></td>
            <td><?php echo $nilai->Nilai5 ?></td>
            <td><?php echo $nilai->Nilai6 ?></td>
            <td><?php echo $nilai->Nilai7 ?></td>
            <td><?php echo $nilai->Nilai8 ?></td>
            <td><?php echo $nilai->Nilai9 ?></td>
            <td><?php echo $nilai->Nilai10 ?></td>
            <td><?php echo $this->tag->linkTo(array("nilai/edit/" . $nilai->RecId, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("nilai/delete/" . $nilai->RecId, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("nilai/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("nilai/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("nilai/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("nilai/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
    <?php 
    }
    else
    {
    ?>
        <tr>
            <td colspan="13">- No data -</td>
        </tr>
    <?php
    }
    ?>
</table>
