<?php

 use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<h1 style="padding-left:2%;">
    Generate Packing Slip
</h1>

<script language="javascript">
    
    function onReject(f){
        var RecId = f.elements.namedItem("RecId").value;

        var Remarks = window.prompt('Keterangan reject '+f.elements.namedItem("PurchReqName").value+' :');

        if(Remarks != null){
            f.elements.namedItem("Remarks").value = Remarks;
            return true;
        } 
        else {
            $(".loader").hide();
            return false;
        }
    }

    
</script>

<table class="table bordered striped hovered" align="center">
    <thead>
        <tr>
            <th>No.</th>
            <th>No. PR</th>
            <th>Tangal</th>
			<th>cabang</th>
           
            <th colspan="4">Action</th>
        </tr>
    </thead>
    <tbody>
        <?php 
        if($page->items != null){
            $i=1;
            if(isset($_GET['page'])){
                if(intval($_GET['page']) > 1) $i += (intval($_GET['page'])-1)*10;
            }
            foreach ($page->items as $konfirmasipembayaran) { ?>
            <tr>
                <td><?php echo $i.'.';?></td><?php $i++;?>
                <td><?php echo $konfirmasipembayaran->PurchReqId ?></td>
                <td><?php echo $konfirmasipembayaran->ApprovalDate ?></td>
				  <td><?php echo $konfirmasipembayaran->nama."/".$konfirmasipembayaran->NamaAreaCabang ?></td>
               

                <?php echo $this->tag->form(array("LaporanData/view", "autocomplete" => "off")) ?>
                <input type="hidden" name="Cabang" value="<?=$konfirmasipembayaran->Cabang?>" />
				 <input type="hidden" name="reqid" value="<?=$konfirmasipembayaran->PurchReqId?>" />
				 <input type="hidden" name="DateFrom" value="<?=$konfirmasipembayaran->ApprovalDate?>" />
				  <input type="hidden" name="Area" value="<?=$konfirmasipembayaran->nama?>" />
				 
                <td><?php echo $this->tag->submitButton("Buat Packing Slip") ?></td>
                </form>

               
              
            </tr>
        <?php } 
        }
        else 
        {
        ?>
            <tr style="text-align:center;">
                <td colspan="7">- No Data -</td>
            </tr>
        <?php
        }
        ?>
    </tbody>
</table>

<div class="place-left">
    <?php echo 'halaman ' . $page->current . " dari " . $page->total_pages ?>
</div>

<div class="place-right">
    <?php echo $this->tag->linkTo(array("purchreqapproval/index", "First", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("purchreqapproval/index?page=" . $page->before, "Previous", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("purchreqapproval/index?page=" . $page->next, "Next", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("purchreqapproval/index?page=" . $page->last, "Last", "class" => "button")) ?>

</div>
