


<style type="text/css">
    @media print{@page {size: A4 landscape}}
</style>

<fieldset border="0px">
	<table class="tablePrint" style="width:100%;">
		<tr>
			<td align="center"><img src="{{ url('img/logo_new_web.png') }}" width="220"></td>
			<td align="center" width="75%"> <h1>Packing Slip</h1></td>
			<td width="20%" align="right">
			<a href="#" id="downloadBtn" class="btn btn-primary pull-right">Download</a>
			<a href="javascript::void();" onclick="window.print();" id="printLink" class="btn btn-success pull-right">Print</a>
			</td>		
		</tr>
		
	</table>
</fieldset>

<fieldset>
<table class="table bordered hovered table2excel" style="table-layout: fixed; border-collapse: collapse">
  
        <tr>
            <td width="100px"  bgcolor="#708090" align="center"><font Color="#FFFFFF">SHIP TO<font></td>  	
        </tr>
		<tr>
           
			<td width="40px"  align="center"></td>  
				<td width="40px"  align="center" hidden></td>  
        </tr>
		<tr>

				<td width="40px"  align="center" hidden></td>  
        </tr>
       
</table>
</fieldset>

<fieldset>
	<table class="table bordered hovered table2excel" style="table-layout: fixed; border-collapse: collapse">
		<tr>
			<td>
				<table border='1px'>
					<tr>
						<td width="40px"  bgcolor="#708090" align="center" colspan="3"><font Color="#FFFFFF">KURIKULUM 2006<font></td>  
			 			
					</tr>
					<tr>
						<td width="40px"  bgcolor="#708090" align="center" ><font Color="#FFFFFF">NO<font></td>
						<td width="150px" bgcolor="#708090" align="center"><font Color="#FFFFFF">DESCRIPTION<font></td> 
						<td width="50px" bgcolor="#708090" align="center"><font Color="#FFFFFF">ORDER QTY<font></td>    			
					</tr>
					
					<tr>
						
						<td class="text-right"></td>
						<td class="text-right"></td>
						<td class="text-right"></td>
						<td class="text-right"></td>
					<tr>
						 <td width="40px" align="center" colspan="2">Total</td>
						<td width="40px" align="center"></td>  
					</tr>
					
				</table>
			</td>
			<td width="100px"></td>
			<td>
				<table  border='1px'>
					<tr>
						<td width="40px"  align="center" bgcolor="#708090" colspan="3"><font Color="#FFFFFF">KURIKULUM 2013<font></td>  
					</tr>
					<tr>
						<td width="40px"  bgcolor="#708090" align="center" ><font Color="#FFFFFF">NO<font></td>
						<td width="150px" bgcolor="#708090" align="center"><font Color="#FFFFFF">DESCRIPTION<font></td> 
						<td width="50px" bgcolor="#708090" align="center"><font Color="#FFFFFF">ORDER QTY<font></td>    
					</tr>
					<tr>
						<td width="40px" align="center">1</td>
						<td width="200px" align="center">SD 3</td>  
						<td width="150px" align="center">-</td> 
					</tr>
					<tr>
						 <td width="40px" align="center" colspan="2">Total</td>
						<td width="40px" align="center"></td>  
					</tr>
				</table>
			</td>
		</tr>     
	</table>
</fieldset>


<fieldset>
<table border="1px">
        <tr>
            <td width="40px"  align="center" bgcolor="#708090" colspan="4"><font Color="#FFFFFF">TSHIRT<font></td>  
			 			
        </tr>
		<tr>
           
			 <td width="40px"  bgcolor="#708090" align="center" ><font Color="#FFFFFF">NO<font></td>
			<td width="150px" bgcolor="#708090" align="center"><font Color="#FFFFFF">DESCRIPTION<font></td> 
			 <td width="40px"  bgcolor="#708090" align="center" ><font Color="#FFFFFF">SIZE<font></td>
			<td width="50px" bgcolor="#708090" align="center"><font Color="#FFFFFF">ORDER QTY<font></td> 
        </tr>
		<tr>
           <td width="40px" align="center">1</td>  
			<td width="40px" align="center">SD</td>  
			<td width="40px" align="center">S</td>
			<td width="40px" align="center">-</td>  
			  						
        </tr>
		<tr>
			<td width="40px" align="center">2</td>  
			<td width="40px" align="center">SMP</td>  
			<td width="40px" align="center">M</td>
			<td width="40px" align="center">-</td>  
									
        </tr>
		<tr>
           <td width="40px" align="center">3</td>  
			<td width="40px" align="center">SMA/SMK</td>  
			<td width="40px" align="center">L</td>
			<td width="40px" align="center">-</td>  
									
        </tr>
	</table>

</fieldset>

<fieldset>
<table class="table bordered hovered table2excel" style="table-layout: fixed; border-collapse: collapse">
  <tr>
	<td>
		<table border='1px'>
			<tr>
				<td width="200px"  align="center" bgcolor="#708090" colspan="4"><font Color="#FFFFFF">PELAKSANA<font></td>  
			 			
			</tr>
		
			<tr height='150px'>
				<td width="100px" align="center"></td>  
				<td width="100px" align="center"></td>  				
			</tr>
		</table>
	</td>
	<td width="150px"></td>
		<td>
			<table  border='1px'>
				<tr>
					 <td width="200px"  align="center" bgcolor="#708090" colspan="4"><font Color="#FFFFFF">PENERIMA<font></td>  
								
				</tr>
				
				<tr height='150px' >
					<td width="200px" align="center"></td>  				
				</tr>
			</table>
		</td>
  </tr>     
</table>
</fieldset>

<fieldset>
<table class="table bordered hovered table2excel" style="table-layout: fixed; border-collapse: collapse">
  
        <tr height='150px'>
            <td width="500px"  bgcolor="#FFFFFF" align="left" >COMMENT</td>  	
        </tr>
		
        
       
</table>
</fieldset>


<div class="place-left"></div>
<div class="place-right">
   
</div>
<script>
    $('#downloadBtn').on('click', function () {
        $(".table2excel").table2excel({
            exclude: ".noExl",
            name: "Primaedu",
            filename: "{{ rpt_title }}.xls"
        });
    });
</script>
