<?php

 use Phalcon\Tag; ?>


<h1>
    <?php echo $this->tag->linkTo(array("deliveryreqheader/index", '<i class="icon-arrow-left-3 fg-darker smaller"></i>')); ?>
    Pengiriman

</h1>

<table class="table bordered striped hovered" align="center">
    <thead>
        <tr>
            <th>Area</th>
            <th>Kode Cabang</th>
            <th>Nama Cabang</th>
            <th>Kode Pembelian</th>
            <th>Tanggal kirim awal</th>
            <th>Status Kirim</th>
            <th colspan="3">Action</th>

        </tr>
    </thead>
    <tbody>
        <?php foreach ($page->items as $purchreqheader) { ?>
            <tr>
                <td><?php echo $purchreqheader->area ?></td>
                <td><?php echo $purchreqheader->kodecabang ?></td>
                <td><?php echo $purchreqheader->namacabang ?></td>
                <td><?php echo $purchreqheader->PurchReqId ?></td>
                <td><?php echo $purchreqheader->ApprovalDate?></td>
                <td><?php echo $purchreqheader->Status ?></td>
				<?php if($purchreqheader->Status === "Draft" || $purchreqheader->Status === "Rejected"||$purchreqheader->Status ==="") { ?>
				<td width="7%"><?php echo $this->tag->linkTo(array("deliveryreqtambah/submit/" . $purchreqheader->RecId, "Submit", "class" => "button primary")); ?></td>

					<td width="7%"><?php echo $this->tag->linkTo(array("deliveryreqtambah/delete/" . $purchreqheader->RecId, "Delete")); ?></td>
				<?php } else { ?>
                  <td width="7%"><?php echo $this->tag->linkTo(array("deliveryreqtambah/kirim/" . $purchreqheader->RecId, "+Pengiriman")); ?></td>
                  
				<?php } ?>
            </tr>
        <?php } ?>
    </tbody>
</table>

<div class="place-left">
    <?php echo 'halaman ' . $page->current . " dari " . $page->total_pages ?>
</div>

<div class="place-right">
    <?php echo $this->tag->linkTo(array("deliveryreqheader/search", "First", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("deliveryreqheader/search?page=" . $page->before, "Previous", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("deliveryreqheader/search?page=" . $page->next, "Next", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("deliveryreqheader/search?page=" . $page->last, "Last", "class" => "button")) ?>

</div>
