

<h1>
    <?php echo $this->tag->linkTo(array("deliveryreqheader/index", '<i class="icon-arrow-left-3 fg-darker smaller"></i>')); ?>

     Pengiriman Buku
  
</h1>


<?php echo $this->getContent(); ?>


<?php echo $this->tag->form(array("deliveryreqline/editQty", "autocomplete" => "off")) ?>

<script type="text/javascript">
    function deleteList(id){
        document.getElementById("item"+id).innerHTML="";
    }
</script>

  <?php echo $this->tag->hiddenField(array("Purchrecheader","size" => 30)) ?>
  <?php echo $this->tag->hiddenField(array("PurchReqId", "size" => 30)) ?>



<table class="table bordered striped hovered" align="center">
    <thead>
        <tr>
            <th>No. Item</th>
			<th>Nama Barang</th>
            <th>Qty Pembelian</th>
            <th>Qty Pengiriman</th>
            <th>Action</th>
         </tr>
    </thead>
    <tbody>
    <?php 
        $i=0;
        foreach ($page->items as $inventreceipt) { 
    ?>
        <tr>
            <tr id="item<?=$i?>">
            <td><?php echo $inventreceipt->ItemId; ?>
			<?php echo $this->tag->hiddenField(array("ItemId[$i]","value"=>$inventreceipt->ItemId, "size" => 30)) ?>
			<?php echo $this->tag->textField(array("Purchreqline"[$i],"value"=>$inventreceipt->RecId, "size" => 30)) ?></td>
            <td><?php echo $inventreceipt->ItemName; ?>
			<?php echo $this->tag->hiddenField(array("ItemName[$i]","value"=>$inventreceipt->ItemName, "size" => 30)) ?>
		
			</td>
            <td><?php echo $inventreceipt->Qty; ?></td>
            <td style="text-align:center;">
                <div class="input-control text" data-role="input-control">
		<?php echo $this->tag->numericField(array("qtyupdate[$i]","value"=>"","size" => 30, "type" => "number", "min" => 1, "max" => 100000)) ?>
                </div>
				</td>
            <td style="text-align:center;"><input type="button" value="Delete" onclick="deleteList(<?=$i?>)"></td>
        </tr>
    <?php 
            $i++;
        }
    ?>
            <tr style="text-align:right;background:#FFF;">
                <td colspan="5"><?php echo $this->tag->submitButton("Post") ?></td>
            </tr>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("deliveryreqheader/viewdetail/$inventreceipt->Purchreqheader/search", "First") ?></td>
    <td><?php echo $this->tag->linkTo("deliveryreqheader/viewdetail/$inventreceipt->Purchreqheader/search?page=" . $page->before, "Previous") ?></td>
    <td><?php echo $this->tag->linkTo("deliveryreqheader/viewdetail/$inventreceipt->Purchreqheader/search?page=" . $page->next, "Next") ?></td>
    <td><?php echo $this->tag->linkTo("deliveryreqheader/viewdetail/$inventreceipt->Purchreqheader/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
</form>
