



<?php echo $this->tag->form("outstanding/create") ?>

<h1>
    <?php echo $this->tag->linkTo(array("Outstanding/index", '<i class="icon-arrow-left-3 fg-darker smaller"></i>')); ?>
    Outstanding
    <small class="on-right">Tambah Baru</small>
</h1>



<?php echo $this->getContent(); ?>

<div class="grid fluid">
    <div class="row">
        <div class="span6">

            <label for="KodeCabang">Kode Cabang</label>
            <div class="input-control text" data-role="input-control">
               <?php echo $this->tag->textField(array("KodeCabang", "size" => 30)) ?>
            </div>

            <label for="Nominal">Nominal</label>
            <div class="input-control text" data-role="input-control">
               <?php echo $this->tag->textField(array("Nominal", "size" => 30)) ?>
            </div>

            <?php echo $this->tag->submitButton("Simpan") ?>
        </div>
    </div>
</div>

</form>
