
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("absensi/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("absensi", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Simpan") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit absensi</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="KodeSiswa">KodeSiswa</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("KodeSiswa", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="AbsenDate">AbsenDate</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("AbsenDate", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="AbsenTime">AbsenTime</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("AbsenTime", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="Cabang">Cabang</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("Cabang", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Simpan") ?></td>
    </tr>
</table>

</form>
