
<?php echo $this->getContent() ?>

<h1>
<small class="place-right">
    <?php echo $this->tag->linkTo("absensi/new", 'Input Presensi<i class="icon-plus on-right smaller"></i>')?>
</small>
</h1>

<?php echo $this->tag->form(array("absensi/search", "autocomplete" => "off")) ?>

<div class="grid fluid">
    <div align="left">
        <h1>Cari presensi siswa</h1>
    </div>

    <div class="row">
        <div class="span6">
            <label for="KodeSiswa">Kode siswa</label>
            <div class="input-control text" data-role="input-control">
                <?php echo $this->tag->textField(array("KodeSiswa", "type" => "number")) ?>
            </div>
            <?php echo $this->tag->submitButton("Cari") ?>
        </div>
    </div>
</div>


<!-- Result View -->
<?php echo $this->tag->form(array("inventreceipt/editQty", "autocomplete" => "off")) ?>

<script type="text/javascript">
    function deleteList(id){
        document.getElementById("item"+id).innerHTML="";
    }
</script>
 
<table class="table bordered striped hovered" align="center">
    <thead>
        <tr>
            <th width="1%">No.</th>
            <th width="10%">Kode Siswa</th>
            <th width="40%">Nama Siswa</th>
            <th width="10%">Login Terakhir</th>
         </tr>
    </thead>
    <tbody>
    <?php 
        //print_r($page->items);
        if(isset($page->items) && count($page->items) > 0){
            $i=1;
            if(isset($_GET["page"])) $i+= (intval($_GET["page"])-1)*10;
            foreach ($page->items as $absensi) { 
    ?>
        <tr>
            <tr id="item<?=$i?>">
            <td><?php echo $i."." ?></td>
            <td><?php echo $absensi->VirtualAccount;//echo $absensi->KodeSiswa; ?></td>
            <td><?php echo $absensi->NamaSiswa; ?></td>
            <td><?php echo $absensi->AbsenTime; ?></td>
        </tr>
    <?php 
                $i++;
            }
    ?>    
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("absensi/index", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("absensi/index?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("absensi/index?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("absensi/index?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
    <?php 
    } 
    else
    { ?>
        <tbody>
            <tr style="text-align:center;">
                <td colspan="4">- No Data -</td>
            </tr>
        </tbody>
    <?php 
    } 
    ?>
</table>
</form>
