
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("inventreceipt/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("inventreceipt", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Simpan") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit inventreceipt</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="Cabang">Cabang</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("Cabang", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="PurchReqLineRecId">PurchReqLineRecId</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("PurchReqLineRecId", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="PackingSlipId">PackingSlipId</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("PackingSlipId", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="ReceiptDate">ReceiptDate</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("ReceiptDate", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="ItemId">ItemId</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("ItemId", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="ItemName">ItemName</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("ItemName", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="QtyReceipt">QtyReceipt</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("QtyReceipt", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="RemainingQty">RemainingQty</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("RemainingQty", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="CreatedBy">CreatedBy</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("CreatedBy", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="CreatedDateTime">CreatedDateTime</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("CreatedDateTime", "type" => "date")) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Simpan") ?></td>
    </tr>
</table>

</form>
