<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("inventreceipt/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("inventreceipt/new", "Create ")); ?>
        </td>
    </tr>
</table>

<?php echo $this->tag->form(array("inventreceipt/editQty", "autocomplete" => "off")) ?>

<script type="text/javascript">
    function deleteList(id){
        document.getElementById("item"+id).innerHTML="";
    }
</script>
 
<table class="table bordered striped hovered" align="center">
    <thead>
        <tr>
            <th>No. Item</th>
            <th>Qty</th>
            <th>Remaining</th>
            <th>Update Qty</th>
            <th>Action</th>
         </tr>
    </thead>
    <tbody>
    <?php 
        $i=0;
        foreach ($page->items as $inventreceipt) { 
    ?>
        <tr>
            <tr id="item<?=$i?>">
            <td><?php echo $inventreceipt->RecId;//echo (isset($item) ? $items->RecId : "-"); ?></td>
            <td><?php echo (isset($inventreceipt) ? $inventreceipt->QtyReceipt : "-"); ?></td>
            <td><?php echo (isset($inventreceipt) ? $inventreceipt->RemainingQty : "-"); ?></td>
            <td style="text-align:center;"><?php echo $this->tag->textField(array("". $inventreceipt->RecId/*"updateQty"*/, "size" => 30)) ?></td>
            <td style="text-align:center;"><input type="button" value="Delete" onclick="deleteList(<?=$i?>)"></td>
        </tr>
    <?php 
            $i++;
        }
    ?>
            <tr style="text-align:right;background:#FFF;">
                <td colspan="5"><?php echo $this->tag->submitButton("Post") ?></td>
            </tr>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("inventreceipt/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("inventreceipt/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("inventreceipt/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("inventreceipt/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
</form>
