
<?php echo $this->tag->form("Konfirmasipembayaranapp/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("Konfirmasi", "Go Back")) ?></td>
    </tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Tambah Pembelian</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="PurchReqId">ID</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("PurchReqId", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="PurchReqName">Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("PurchReqName", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="Requester">Requester</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("Requester", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="PurchReqDate">Request Date</label>
        </td>
        <td align="left">
                <?php echo $this->tag->datefield(array("PurchReqDate", "type" => "date", "value" => date('Y-m-d') )) ?>
        </td>
    </tr>
    
    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Simpan") ?></td>
    </tr>
</table>

</form>
