
<?php echo $this->getContent(); ?> 

<h1>
    <?php echo $this->tag->linkTo(array("deliveryreqless/", '<i class="icon-arrow-left-3 fg-darker smaller"></i>')); ?>
    Pengiriman Approval
    <small class="on-right">Detail Pengiriman</small>
</h1>


<table class="table bordered striped hovered">
    <thead>
        <tr>
            <th>No.</th>
            <th>Kode Barang</th>
            <th>Nama Barang</th>
            <th>Permintaan Pembelian</th>
            <th>Total Pengiriman</th>
        </tr>
    </thead>
    <tbody>
    <?php 
    if(isset($page)){
        if($page->items != null){
            $i=1;
            if(isset($_GET['page'])){
                if(intval($_GET['page']) > 1) $i += (intval($_GET['page'])-1)*10;
            }
        foreach ($page->items as $purchreqline) { ?>
        <tr>
            <td align="right">
                <label for="PurchReqId"><?php echo $i.".";?></label><?php $i++;?>
            </td>
            <td align="left">
                <?php echo $purchreqline->ItemId; ?>
            </td>
            <td align="left">
                <?php echo $purchreqline->ItemName; ?>
            </td>
            <td align="left">
                <?php echo $purchreqline->Qty; ?>
            </td>
            <td align="left">
                <?php echo $purchreqline->QtyRemaining; ?>
            </td>
        </tr>
        <?php }
        } 
        }
        else 
        {
        ?>
            <tr style="text-align:center;">
                <td colspan="4">- No Data -</td>
            </tr>
        <?php
        }
        ?>

    </tbody>
</table>

<div class="place-left">
    <?php echo 'halaman ' . $page->current . " dari " . $page->total_pages ?>
</div>

<div class="place-right">
    <?php echo $this->tag->linkTo(array("deliveryreqapproval/edit/$purchreqlineRecId", "First", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("deliveryreqapproval/edit/".$purchreqlineRecId."?page=" . $page->before, "Previous", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("deliveryreqapproval/edit/".$purchreqlineRecId."?page=" . $page->next, "Next", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("deliveryreqapproval/edit/".$purchreqlineRecId."?page=" . $page->last, "Last", "class" => "button")) ?>

</div> 