<?php

 use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<h1>
    <?php echo $this->tag->linkTo(array("deliveryreqless/index", '<i class="icon-arrow-left-3 fg-darker smaller"></i>')); ?>
    Pembelian

    <small class="place-right">
        <?php echo $this->tag->linkTo(array("deliveryreqless/new", 'Tambah<i class="icon-plus on-right smaller"></i>')); ?>    
    </small>
</h1>

<table class="table bordered striped hovered" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Requester</th>
            <th>Date</th>
            <th>Status</th>
            <th colspan="4">Action</th>

        </tr>
    </thead>
    <tbody>
        <?php foreach ($page->items as $purchreqheader) { ?>
            <tr>
                <td><?php echo $purchreqheader->PurchReqId ?></td>
                <td><?php echo $purchreqheader->PurchReqName ?></td>
                <td><?php echo $purchreqheader->Requester ?></td>
                <td><?php echo $purchreqheader->PurchReqDate ?></td>
                <td><?php echo $purchreqheader->Status ?></td>
                <td><?php echo $this->tag->linkTo(array("purchreqheader/edit/" . $purchreqheader->RecId, "Approved")); ?></td>
                <td><?php echo $this->tag->linkTo(array("purchreqheader/delete/" . $purchreqheader->RecId, "Reject")); ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>

<div class="place-left">
    <?php echo 'halaman ' . $page->current . " dari " . $page->total_pages ?>
</div>

<div class="place-right">
    <?php echo $this->tag->linkTo(array("purchreqheader/search", "First", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("purchreqheader/search?page=" . $page->before, "Previous", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("purchreqheader/search?page=" . $page->next, "Next", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("purchreqheader/search?page=" . $page->last, "Last", "class" => "button")) ?>

</div>
