<?php

 use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<h1>
    <?php echo $this->tag->linkTo(array("invoice/index", '<i class="icon-arrow-left-3 fg-darker smaller"></i>')); ?>
    Invoice <small>Pembelian Smartbook</small>
</h1>

<table class="table bordered striped hovered" align="center">
    <thead>
        <tr>
            <th>Kode Pembelian</th>
            <th>Deskripsi</th>
            <th>Requester</th>
            <th>Tanggal</th>
            <th colspan="3">Action</th>

        </tr>
    </thead>
    <tbody>
        <?php foreach ($page->items as $purchreqheader) { ?>
            <tr>
                <td><?php echo $purchreqheader->PurchReqId ?></td>
                <td><?php echo $purchreqheader->PurchReqName ?></td>
                <td><?php echo $purchreqheader->Requester ?></td>
                <td><?php echo $purchreqheader->PurchReqDate ?></td>
                <td width="15%" align="center"><?php echo $this->tag->linkTo(array("invoice/invoice/" . $purchreqheader->RecId, "<b>Lihat Invoice</b>")); ?></td>
           </tr>
        <?php } ?>
    </tbody>
</table>
