<?php

 use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<h1>
    <?php echo $this->tag->linkTo(array("inventitem/index", '<i class="icon-arrow-left-3 fg-darker smaller"></i>')); ?>
    Item

    <small class="place-right">
        <?php echo $this->tag->linkTo(array("inventitem/new", 'Tambah Baru<i class="icon-plus on-right smaller"></i>')); ?>    
    </small>
</h1>

<table class="table bordered striped hovered" >
    <thead>
        <tr>
            <th>Kode Item</th>
            <th>Nama Item</th>
            <th colspan="2">Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($page->items as $inventitem) { ?>
            <tr>
                <td><?php echo $inventitem->KodeItem ?></td>
                <td><?php echo $inventitem->NamaItem ?></td>
                <td><?php echo $this->tag->linkTo(array("inventitem/edit/" . $inventitem->KodeItem, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("inventitem/delete/" . $inventitem->KodeItem, "Delete")); ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>

<div class="place-left"><?php echo 'halaman ' . $page->current, " dari ", $page->total_pages ?></div>

<div class="place-right">
    <?php echo $this->tag->linkTo(array("inventitem/search", "First", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("inventitem/search?page=" . $page->before, "Previous", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("inventitem/search?page=" . $page->next, "Next", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("inventitem/search?page=" . $page->last, "Last", "class" => "button")) ?>
</div>
