<?php

 use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<h1>
    <?php echo $this->tag->linkTo(array("purchreqheader/index", '<i class="icon-arrow-left-3 fg-darker smaller"></i>')); ?>
    Pembelian

    <small class="place-right">
        <?php echo $this->tag->linkTo(array("purchreqheader/new", 'Tambah<i class="icon-plus on-right smaller"></i>')); ?>    
    </small>
</h1>

<table class="table bordered striped hovered" align="center">
    <thead>
        <tr>
            <th>Kode Pembelian</th>
            <th>Deskripsi</th>
            <th>Requester</th>
            <th>Tanggal</th>
            <th>Status</th>
            <th colspan="3">Action</th>

        </tr>
    </thead>
    <tbody>
        <?php foreach ($page->items as $purchreqheader) { ?>
            <tr>
                <td><?php echo $purchreqheader->PurchReqId ?></td>
                <td><?php echo $purchreqheader->PurchReqName ?></td>
                <td><?php echo $purchreqheader->Requester ?></td>
                <td><?php echo $purchreqheader->PurchReqDate ?></td>
                <td><?php echo $purchreqheader->Status ?></td>
				<?php if($purchreqheader->Status === "Draft" || $purchreqheader->Status === "Rejected") { ?>
					<td width="7%"><?php echo $this->tag->linkTo(array("purchreqheader/submit/" . $purchreqheader->RecId, "Submit", "class" => "button primary")); ?></td>
					<td width="7%"><?php echo $this->tag->linkTo(array("purchreqheader/edit/" . $purchreqheader->RecId, "Edit")); ?></td>
					<td width="7%"><?php echo $this->tag->linkTo(array("purchreqheader/delete/" . $purchreqheader->RecId, "Delete")); ?></td>
				<?php } elseif ($purchreqheader->Status === "Approved"){ ?>
                                        <td width="7%"><?php echo $this->tag->linkTo(array("purchreqheader/viewdetail/" . $purchreqheader->RecId, "Detail")); ?>
										</td><td><?php echo $this->tag->linkTo(array("purchreqheader/invoice/" .$purchreqheader->RecId, "Invoice")); ?>
										
				<?php }else {?>
				  <td width="7%"><?php echo $this->tag->linkTo(array("purchreqheader/viewdetail/" . $purchreqheader->RecId, "Detail")); ?>
					<?php }?>
		   </tr>
        <?php } ?>
    </tbody>
</table>

<div class="place-left">
    <?php echo 'halaman ' . $page->current . " dari " . $page->total_pages ?>
</div>

<div class="place-right">
    <?php echo $this->tag->linkTo(array("purchreqheader/search", "First", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("purchreqheader/search?page=" . $page->before, "Previous", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("purchreqheader/search?page=" . $page->next, "Next", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("purchreqheader/search?page=" . $page->last, "Last", "class" => "button")) ?>

</div>
