
<?php

 use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<h3 align="center">
<strong>  
<?php foreach ($result2 as $row2) { ?>
Barcode :
<?php echo $row2->Barcode; ?> 
|| 
<?php echo $row2->NamaItem; ?>

<?php } ?>
</strong>
</h3>
<table class="table bordered striped hovered" align="center">
    <thead>
        <tr>
            <th>No.</th>
            <th>Cabang</th>
            <th>PR</th>
            <th>Keterangan</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody  align="center">
        <?php 
        if($result != null){
            $i=1;
            foreach ($result as $row) { ?>

           <?php echo $this->tag->form(array("barcodeinvalid/savedelete", "autocomplete" => "off")) ?>

            <input type="hidden" name="RecId" value="<?php echo $row->RecID ;?>">
            <input type="hidden" name="Cabang" value="<?php echo $row->Cabang ;?>">
            <input type="hidden" name="Barcode" value="<?php echo $row->Barcode ;?>">
            <input type="hidden" name="CreatedAt" value="<?php echo $row->CreatedAt ;?>">
            <input type="hidden" name="CreatedBy" value="<?php echo $row->CreatedBy ;?>">
            <input type="hidden" name="PurchReqId" value="<?php echo $row->PurchReqId ;?>">
            <input type="hidden" name="TypeUpload" value="<?php echo $row->TypeUpload ;?>">
            <input type="hidden" name="Status" value="<?php echo $row->Status ;?>">
            <tr>
                <td><?php echo $i.'.';?></td><?php $i++;?>
                <td><?php echo $row->KodeAreaCabang .'-'. $row->NamaAreaCabang ?></td>
                <td><?php echo $row->PR ?></td>
            <td>
            <div class="input-control text" data-role="input-control">
                <input type="text" name="Keterangan" value=""></td>
            </div>
            </td>
                <td>
                <?php echo $this->tag->submitButton("Simpan") ?>
                </td>
            </tr>
            </form>

        <?php } 
        }
        else 
        {
        ?>
            <tr style="text-align:center;">
                <td colspan="7">- No Data -</td>
            </tr>
        <?php
        }
        ?>
    </tbody>
</table>