
<?php echo $this->tag->form(array("scheduleheader/create", "enctype" => "multipart/form-data")) ?>

<h1>
    <?php echo $this->tag->linkTo(array("scheduleheader", '<i class="icon-arrow-left-3 fg-darker smaller"></i>')); ?>
    Jadwal
    <small class="on-right">Tambah Baru</small>
</h1>

<?php echo $this->getContent(); ?>

<div class="grid fluid">
    <div class="row">
        <div class="span6">
            <label for="TahunAjaran">Tahun Ajaran</label>
            <div class="input-control select" data-role="input-control">
                <?php echo $this->tag->select(["TahunAjaran", $tahunajaran, 'using' => ['RecID', 'Description'],
                    'useEmpty' => true, 'emptyText' => '---', 'emptyValue' => '0']) ?>
            </div>
            <label for="Description">Deskripsi</label>
            <div class="input-control text" data-role="input-control">
                <?php echo $this->tag->textField(array("Description", "size" => 30)) ?>
            </div>
            <label for="Program">Program</label>
            <div class="input-control select" data-role="input-control">
                <?php
                echo $this->tag->select(array("Program", $program, "using" => array("RecID", "NamaProgram"),
                    'useEmpty' => true, 'emptyText' => '---', 'emptyValue' => ''))
                ?>
            </div>
           
        </div>
    </div>
	<div class="row">
		<div class="span6">
			<?php echo $this->tag->submitButton("Simpan") ?>
		</div>
	</div>
</div>

</form> 
