<?php

 use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<h1>
    <?php echo $this->tag->linkTo(array("scheduleheader/index", '<i class="icon-arrow-left-3 fg-darker smaller"></i>')); ?>
    Jadwal

    <small class="place-right">
        <?php echo $this->tag->linkTo(array("scheduleheader/new", 'Tambah<i class="icon-plus on-right smaller"></i>')); ?>    
    </small>
</h1>

<table class="table bordered striped hovered">
    <thead>
        <tr>
            <th>Kode Jadwal</th>
            <th>Description</th>
            <th>Program</th>
            <th colspan="2">Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($page->items as $scheduleheader) { ?>
            <tr>
                <td><?php echo $scheduleheader->KodeJadwal ?></td>
                <td><?php echo $scheduleheader->Description ?></td>
                <td><?php echo $scheduleheader->getNamaProgram() ?></td>
                <td><?php echo $this->tag->linkTo(array("scheduleheader/edit/" . $scheduleheader->RecId, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("scheduleheader/delete/" . $scheduleheader->RecId, "Delete")); ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>


<div class="place-left"><?php echo 'halaman ' . $page->current, " dari ", $page->total_pages ?></div>

<div class="place-right">
    <?php echo $this->tag->linkTo(array("scheduleheader/search", "First", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("scheduleheader/search?page=" . $page->before, "Previous", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("scheduleheader/search?page=" . $page->next, "Next", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("scheduleheader/search?page=" . $page->last, "Last", "class" => "button")) ?>
</div>
