<div class="grid fluid">
    <div class="row">
        <img src="public/img/under-maintenance.jpg">
    </div>
</div>
<style>
img { 
    width:100%; 
    pointer-events: none;
}
</style>
<!-- <?php echo $this->getContent() ?>

<h1>
    <small class="place-right">
        <?php echo $this->tag->linkTo(array("Konfirmasipembayaran/new", 'Tambah Baru<i class="icon-plus on-right smaller"></i>')); ?>    
    </small>
</h1>

<?php echo $this->tag->form(array("Konfirmasipembayaran/search", "autocomplete" => "off")) ?>

<div align="left">
    <h1>Cari detail pembayaran</h1>
</div>

<div class="grid fluid">
    <div class="row">
        <div class="span6">

            <label for="Confirmreqid">Kode Pembayaran</label>
            <div class="input-control text" data-role="input-control">
                <?php echo $this->tag->textField(array("Confirmreqid", "size" => 30,'required')) ?>
            </div>

            <label for="PurchReqName">Deskripsi</label>
            <div class="input-control text" data-role="input-control">
                <?php echo $this->tag->textField(array("PurchReqName", "size" => 30)) ?>
            </div>

            <label for="Nominal">Jumlah yang di bayarkan</label>
            <div class="input-control text" data-role="input-control" >
                <?php echo $this->tag->textField(array("Nominal", "size" => 30)) ?>
            </div>

            <label for="PurchReqDate">Tanggal</label>
            <div class="input-control text" data-role="datepicker" data-effect="slide" data-format="yyyy-mm-dd">
                <?php echo $this->tag->textField(array("PurchReqDate", "size" => 30)) ?>
            </div>

            <label for="Status">Status</label>
            <div class="input-control select" data-role="input-control">
                <?php echo $this->tag->selectStatic("Status", array("" => " --- ","Draft"=> "Draft", "Inreview"=> "Inreview", "Approved"=> "Approved", "Rejected"=> "Rejected", "Canceled" => "Canceled")) ?>
            </div>

            <?php echo $this->tag->submitButton("Cari") ?>
        </div>
    </div>
</div>

</form>
 -->