<?php

 use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<h1>
    <?php echo $this->tag->linkTo(array("Konfirmasipembayaran/index", '<i class="icon-arrow-left-3 fg-darker smaller"></i>')); ?>
    Konfirmasi Pembayaran

    <small class="place-right">
        <?php echo $this->tag->linkTo(array("Konfirmasipembayaran/new", 'Tambah<i class="icon-plus on-right smaller"></i>')); ?>    
    </small>
</h1>

<table class="table bordered striped hovered" align="center">
    <thead>
        <tr>
			 <th>Kode Konfirmasi</th>
            <th>Kode Pembelian</th>
            <th>Deskripsi</th>
            <th>Nominal</th>
            <th>Tanggal</th>
            <th>Status</th>
            <th colspan="3">Action</th>

        </tr>
    </thead>
    <tbody>
        <?php foreach ($page->items as $Konfirmasipembayaran) { ?>
            <tr>
                <td><?php echo $Konfirmasipembayaran->ConfirmId ?></td>
				 <td><?php echo $Konfirmasipembayaran->PurchReqId?></td>
                <td><?php echo $Konfirmasipembayaran->PurchReqName ?></td>
                <td><?php echo $Konfirmasipembayaran->Nominal ?></td>
                <td><?php echo $Konfirmasipembayaran->PurchReqDate ?></td>
                <td><?php echo $Konfirmasipembayaran->Status ?></td>
				<?php if($Konfirmasipembayaran->Status === "Draft") { ?>
					<td width="7%"><?php echo $this->tag->linkTo(array("Konfirmasipembayaran/submit/" . $Konfirmasipembayaran->RecId, "Submit", "class" => "button primary")); ?></td>
					<td width="7%"><?php echo $this->tag->linkTo(array("Konfirmasipembayaran/edit/" . $Konfirmasipembayaran->RecId, "Edit")); ?></td>
					<td width="7%"><?php echo $this->tag->linkTo(array("Konfirmasipembayaran/delete/" . $Konfirmasipembayaran->RecId, "Delete")); ?></td>
				<?php } elseif( $Konfirmasipembayaran->Status === "OnHold") { ?>
				<td width="7%"><?php echo $this->tag->linkTo(array("Konfirmasipembayaran/new/", " +konfirmasi", "class" => "button primary")); ?></td>
                     <td width="7%"><?php echo $this->tag->linkTo(array("Konfirmasipembayaran/viewdetail/" . $Konfirmasipembayaran->RecId, "Detail")); ?></td>
				<?php }elseif( $Konfirmasipembayaran->Status === "Rejected"){ ?>
				<td width="7%"><?php echo $this->tag->linkTo(array("Konfirmasipembayaran/submit/" . $Konfirmasipembayaran->RecId, "Submit", "class" => "button primary")); ?></td>
					<td width="7%"><?php echo $this->tag->linkTo(array("Konfirmasipembayaran/edit/" . $Konfirmasipembayaran->RecId, "Edit")); ?></td>
					<td width="7%"><?php echo $this->tag->linkTo(array("Konfirmasipembayaran/delete/" . $Konfirmasipembayaran->RecId, "Delete")); ?></td>
					<?php } elseif( $Konfirmasipembayaran->Status === "Approved") { ?>
						  <td width="7%"><?php echo $this->tag->linkTo(array("Konfirmasipembayaran/Kwitansi/" . $Konfirmasipembayaran->RecId, "Kwitansi")); ?></td>
							 
           
        <?php }else{?>
		   <td width="7%"><?php echo $this->tag->linkTo(array("Konfirmasipembayaran/viewdetail/" . $Konfirmasipembayaran->RecId, "Detail")); ?></td>
		 
		 </tr>
        <?php } }?>
    </tbody>
</table>

<div class="place-left">
    <?php echo 'halaman ' . $page->current . " dari " . $page->total_pages ?>
</div>

<div class="place-right">
    <?php echo $this->tag->linkTo(array("Konfirmasipembayaran/search", "First", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("Konfirmasipembayaran/search?page=" . $page->before, "Previous", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("Konfirmasipembayaran/search?page=" . $page->next, "Next", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("Konfirmasipembayaran/search?page=" . $page->last, "Last", "class" => "button")) ?>

</div>
