<?php

 use Phalcon\Tag; ?>


<h1>
    <?php echo $this->tag->linkTo(array("deliveryreqheader/index", '<i class="icon-arrow-left-3 fg-darker smaller"></i>')); ?>
    Pengiriman

</h1>

<table class="table bordered striped hovered" align="center">
    <thead>
        <tr>
            <th>Area</th>
            <th>Kode Cabang</th>
            <th>Nama Cabang</th>
            <th>Kode Pembelian</th>
      
            <th colspan="2">Action</th>

        </tr>
    </thead>
    <tbody>
        <?php foreach ($page->items as $purchreqheader) { ?>
           
		<?php if($purchreqheader->statuskirim === "Draft" || $purchreqheader->statuskirim === "Inreview"||
		$purchreqheader->statuskirim === "Approved") { ?>
                
		<?php }else{ ?>
		 <tr>
				<td><?php echo $purchreqheader->area ?></td>
                <td><?php echo $purchreqheader->kodecabang ?></td>
                <td><?php echo $purchreqheader->namacabang ?></td>
                <td><?php echo $purchreqheader->PurchReqId ?></td>
				<td><?php echo $this->tag->linkTo(array("deliveryreqheader/create/" . $purchreqheader->PurchReqId, "Input barang yang akan dikirim")); ?></td>
          </tr>
				<?php }} ?>
				  
    </tbody>
</table>

<div class="place-left">
    <?php echo $this->tag->linkTo(array("deliveryreqheader/search", "First", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("deliveryreqheader/search?page=" . $page->before, "Previous", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("deliveryreqheader/search?page=" . $page->next, "Next", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("deliveryreqheader/search?page=" . $page->last, "Last", "class" => "button")) ?>

</div>
