
<?php echo $this->tag->form("ruangan/create") ?>

<h1>
    <?php echo $this->tag->linkTo(array("ruangan/index", '<i class="icon-arrow-left-3 fg-darker smaller"></i>')); ?>
    Ruangan
    <small class="on-right">Tambah Baru</small>
</h1>

<?php echo $this->getContent(); ?>

<div class="grid fluid">
    <div class="row">
        <div class="span6">
            
            <label for="KodeRuangan">Kode Ruangan</label>
            <div class="input-control text" data-role="input-control">
                <?php echo $this->tag->textField(array("KodeRuangan", "size" => 30)) ?>
            </div>
            
            <label for="NamaRuangan">Nama Ruangan</label>
            <div class="input-control text" data-role="input-control">
                <?php echo $this->tag->textField(array("NamaRuangan", "size" => 30)) ?>
            </div>
            
            <label for="Kapasitas">Kapasitas</label>
            <div class="input-control text" data-role="input-control">
                <?php echo $this->tag->textField(array("Kapasitas", "size" => 30)) ?>
            </div>

            <?php echo $this->tag->submitButton("Simpan") ?>
        </div>
    </div>
</div>

</form>
