<?php
 use Phalcon\Tag; ?>
 <?php echo $this->getContent(); ?>

<h1>
<?php echo $this->tag->linkTo(array("ruangan/index", '<i class="icon-arrow-left-3 fg-darker smaller"></i>')); ?>
    Ruangan

    <small class="place-right">
<?php echo $this->tag->linkTo(array("ruangan/new", 'Tambah Baru<i class="icon-plus on-right smaller"></i>')); ?>    
    </small>
</h1>

<table class="table bordered striped hovered" align="center">
    <thead>
        <tr>
            <th>Kode Ruangan</th>
            <th>Nama Ruangan</th>
            <th>Kapasitas</th>
            <th colspan="2">Action</th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($page->items as $ruangan) { ?>
            <tr>
                <td><?php echo $ruangan->KodeRuangan ?></td>
                <td><?php echo $ruangan->NamaRuangan ?></td>
                <td><?php echo $ruangan->Kapasitas ?></td>
                <td><?php echo $this->tag->linkTo(array("ruangan/edit/" . $ruangan->RecID, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("ruangan/delete/" . $ruangan->RecID, "Delete")); ?></td>
            </tr>
<?php } ?>
    </tbody>
</table>

<div class="place-left"><?php echo 'halaman ' . $page->current, " dari ", $page->total_pages ?></div>

<div class="place-right">
    <?php echo $this->tag->linkTo(array("ruangan/search", "First", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("ruangan/search?page=" . $page->before, "Previous", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("ruangan/search?page=" . $page->next, "Next", "class" => "button")) ?>
    <?php echo $this->tag->linkTo(array("ruangan/search?page=" . $page->last, "Last", "class" => "button")) ?>
</div>
