
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("deliveryreqline/new", "Create purchreqline")) ?>
</div>

<?php echo $this->tag->form(array("deliveryreqline/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search deliveryreqline</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="RecId">RecId</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("RecId", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="Deliveryreqheader">Deliveryreqheader</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("Deliveryreqheader", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="ItemId">ItemId</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("ItemId", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="ItemName">ItemName</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("ItemName", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="Qty">Qty</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("Qty", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="IsReceipt">IsReceipt</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("IsReceipt", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="CreatedBy">CreatedBy</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("CreatedBy", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="CreatedDateTime">CreatedDateTime</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("CreatedDateTime", "type" => "date")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Cari") ?></td>
    </tr>
</table>

</form>
